# Generated by Django 6.0 on 2026-01-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(max_length=255, verbose_name='دسته\u200cبندی')),
                ('status', models.CharField(choices=[('open', 'باز'), ('pending', 'درحال بررسی'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('execution_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان اجرا')),
                ('execution_location', models.CharField(blank=True, max_length=500, null=True, verbose_name='محل اجرا')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_ads', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ad.ad', verbose_name='آگهی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
            },
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
