# Generated by Django 6.0 on 2026-01-02 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_response_delete_ads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_performed', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('assigned', 'تخصیص شده'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
