# Generated by Django 6.0 on 2026-01-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_ad_creator_alter_ad_performer_alter_ad_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('assigned', 'تخصیص شده'), ('done_reported', 'اعلام پایان کار'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت'),
        ),
    ]
