# Generated by Django 6.0 on 2026-01-03 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_remove_adrequest_unique_request_per_ad_performer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adrequest',
            name='unique_request_per_ad_performer',
        ),
        migrations.AddConstraint(
            model_name='adrequest',
            constraint=models.UniqueConstraint(fields=('ad', 'requester'), name='unique_request_per_ad_requester'),
        ),
    ]
