# Generated by Django 6.0 on 2026-01-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_remove_adrequest_unique_request_per_ad_performer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adrequest',
            name='unique_request_per_ad_requester',
        ),
    ]
