# Generated by Django 6.0 on 2026-01-03 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_remove_adrequest_unique_request_per_ad_requester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='adrequest',
            old_name='requester',
            new_name='performer',
        ),
        migrations.AddConstraint(
            model_name='adrequest',
            constraint=models.UniqueConstraint(fields=('ad', 'performer'), name='unique_request_per_ad_performer'),
        ),
    ]
