# Generated by Django 6.0 on 2026-01-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_rename_requester_adrequest_performer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adrequest',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='adrequest',
            name='unique_request_per_ad_performer',
        ),
    ]
