# Generated by Django 6.0 on 2026-01-05 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_alter_adrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست', 'verbose_name_plural': 'درخواست\u200cها'},
        ),
        migrations.AddConstraint(
            model_name='adrequest',
            constraint=models.UniqueConstraint(fields=('ad', 'performer'), name='unique_request_per_ad_performer'),
        ),
    ]
