# Generated by Django 6.0 on 2026-01-03 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0003_alter_ad_creator_alter_ad_performer_alter_ad_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ad.ad', verbose_name='آگهی')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL, verbose_name='پیمانکار')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ad', 'performer'), name='unique_request_per_ad_performer')],
            },
        ),
    ]
