# Generated by Django 6.0 on 2026-01-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست', 'verbose_name_plural': 'درخواست\u200cها'},
        ),
    ]
