# Generated by Django 6.0 on 2026-01-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('customer', 'مشتری'), ('performer', 'پیمانکار'), ('support', 'پشتیبانی'), ('admin', 'مدیر')], max_length=50, unique=True),
        ),
    ]
