# Generated by Django 6.0 on 2026-01-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='میانگین امتیاز'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_ads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد آگهی\u200cهای انجام شده'),
        ),
    ]
