# Generated by Django 6.0 on 2026-01-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_alter_adrequest_options_and_more'),
        ('comment', '0003_alter_comment_content'),
        ('user', '0006_profile_average_rating_profile_completed_ads_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='completed_ads_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='ads',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='ad.ad', verbose_name='آگهی\u200cها'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد آگهی\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='comment.comment', verbose_name='نظرات'),
        ),
    ]
