# Generated by Django 6.0 on 2026-01-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_completed_ads_count_profile_ads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ads_count',
        ),
    ]
