# Generated by Django 6.0 on 2026-01-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_content_alter_comment_performer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True, verbose_name='متن نظر'),
        ),
    ]
