# Generated by Django 6.0 on 2026-01-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='performer',
        ),
    ]
