# Generated by Django 6.0 on 2026-01-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_alter_adrequest_options_and_more'),
        ('tickets', '0002_alter_ticket_options_remove_ticket_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ad',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ad.ad', verbose_name='آگهی'),
        ),
    ]
